version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/nyt/app
    environment:
      - NODE_ENV=development
      - DEBUG=*
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
    links:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./app/public:/home/nginx/public
    restart: unless-stopped

  varnish:
    build:
      context: .
      dockerfile: ./varnish/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - nginx
    links:
      - nginx
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    restart: unless-stopped
